# Generated by Django 3.1.6 on 2021-02-03 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 9, 13, 49, 869973, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
