# Generated by Django 3.1.6 on 2021-02-03 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_auto_20210203_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 25, 21, 388545, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='Publication date')),
                ('total_songs', models.IntegerField(verbose_name='Total songs')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.band')),
            ],
        ),
    ]
