# Generated by Django 3.1.6 on 2021-02-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0004_auto_20210203_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.band', verbose_name='Band'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField()),
                ('cd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.cd', verbose_name='CD')),
            ],
        ),
    ]
