# Generated by Django 3.1.6 on 2021-02-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_auto_20210204_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='cd_id',
            new_name='cd',
        ),
    ]
