# Generated by Django 3.1.6 on 2021-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0006_auto_20210204_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='total_songs',
            field=models.IntegerField(default=0, verbose_name='Total songs'),
        ),
    ]
